"""Standardized API exceptions and error response handlers."""

from .exceptions import (
    ApiError,
    ApiException,
    CheckViolationError,
    ConflictError,
    ExclusionViolationError,
    ForbiddenError,
    ForeignKeyViolationError,
    IntegrityViolationError,
    InvalidFacetFilterError,
    InvalidOrderFieldError,
    InvalidSearchColumnError,
    LockTimeoutError,
    NoSearchableFieldsError,
    NotFoundError,
    NotNullViolationError,
    PoolExhaustedError,
    UnauthorizedError,
    UniqueViolationError,
    UnsupportedFacetTypeError,
    from_integrity_error,
    generate_error_responses,
)
from .handler import init_exceptions_handlers

__all__ = [
    "ApiError",
    "ApiException",
    "CheckViolationError",
    "ConflictError",
    "ExclusionViolationError",
    "ForbiddenError",
    "ForeignKeyViolationError",
    "IntegrityViolationError",
    "InvalidFacetFilterError",
    "InvalidOrderFieldError",
    "InvalidSearchColumnError",
    "LockTimeoutError",
    "NoSearchableFieldsError",
    "NotFoundError",
    "NotNullViolationError",
    "PoolExhaustedError",
    "UnauthorizedError",
    "UniqueViolationError",
    "UnsupportedFacetTypeError",
    "from_integrity_error",
    "generate_error_responses",
    "init_exceptions_handlers",
]
